version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing npm packages...
      - cd ./my-app
      - npm install

  pre_build:
    commands:
      - echo "Preparing for build..."

  build:
    commands:
      - echo "Running tests..."
      - CI=true npm run test:junit
      - ls -la my-app
      - cat my-app/junit.xml
  post_build:
    commands:
      - echo "Build completed on `date`"          
reports:
  jest_reports:
    files:
      - junit.xml
    file-format: JUNITXML
    base-directory: my-app
