version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd ./my-app
      - echo Installing npm packages...
      - npm install
  build:
    commands:
      - echo Run tests...
      - CI=true npm run test:junit
      - ls -la my-app
      - cat my-app/junit.xml
            
reports:
  jest_reports:
    files:
      - junit.xml
    file-format: JUNITXML
    base-directory: my-app
